# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            James Munnelly
tagline:          'Containers, Kubernetes, Golang'
description:      ''
url:              https://mnrz.xyz
baseurl:          /

author:
  name:           'James Munnelly'

paginate:         5

config:
  ga: UA-85898356-1

github:
  url:            https://github.com/munnerz

twitter:
  url:            https://twitter.com/jamesmunnelly

gems:
  - jekyll-sitemap

exclude:
- Gemfile
- Gemfile.lock