# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            James Munnelly
tagline:          'Containers, Kubernetes, Golang'
description:      ''
url:              https://mnrz.xyz
baseurl:          /

author:
  name:           'James Munnelly'

paginate:         5

# Custom vars
version:          2.1.0

github:
  url:            https://github.com/munnerz

twitter:
  url:            https://twitter.com/jamesmunnelly

exclude:
- Gemfile
- Gemfile.lock